language: node_js
sudo: false
node_js:
- "6"
cache:
  directories:
  - node_modules
matrix:
  include:
  - os: linux
    sudo: required
    dist: trusty
    compiler: g++
  - os: osx
    osx_image: xcode7
    compiler: clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - xutils-dev
    - libxi-dev
    - libxxf86vm-dev
    - x11proto-xf86vidmode-dev
    - mesa-utils
    - xvfb
    - libgl1-mesa-dri
    - libglapi-mesa
    - libosmesa6
script:
- npm run ci
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
